version: '3'
services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /Users/nikita/chat/build/nginx:/etc/nginx